INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Blusa Emily 01', 3200, 20, './img/imagenes_producto_blusas/1.jpg', 'Blusas y Camisas');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Blusa Emily 02', 3200, 20, './img/imagenes_producto_blusas/2.jpg', 'Blusas y Camisas');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Blusa Emily 03', 3200, 20, './img/imagenes_producto_blusas/3.jpg', 'Blusas y Camisas');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Blusa Emily 04', 3200, 20, './img/imagenes_producto_blusas/4.jpg', 'Blusas y Camisas');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Blusa Emily 05', 3200, 20, './img/imagenes_producto_blusas/5.jpg', 'Blusas y Camisas');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Abrigo Emily 01', 6700, 7, './img/imagenes_producto_abrigos/1.jpg', 'Abrigos');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Abrigo Emily 02', 6700, 7, './img/imagenes_producto_abrigos/2.jpg', 'Abrigos');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Abrigo Emily 03', 6700, 7, './img/imagenes_producto_abrigos/3.jpg', 'Abrigos');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Pantalon Emily 01', 4500, 10, './img/imagenes_producto_pantalones/1.jpg', 'Pantalones');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Pantalon Emily 02', 4500, 10, './img/imagenes_producto_pantalones/2.jpg', 'Pantalones');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Pantalon Emily 03', 4500, 10, './img/imagenes_producto_pantalones/3.jpg', 'Pantalones');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Pantalon Emily 04', 4500, 10, './img/imagenes_producto_pantalones/4.jpg', 'Pantalones');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Remera Emily 01', 2500, 20, './img/imagenes_producto_remeras/1.jpg', 'Remeras');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Remera Emily 02', 2500, 20, './img/imagenes_producto_remeras/2.jpg', 'Remeras');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Remera Emily 03', 2500, 20, './img/imagenes_producto_remeras/3.jpg', 'Remeras');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Remera Emily 04', 2500, 20, './img/imagenes_producto_remeras/4.jpg', 'Remeras');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Remera Emily 05', 2500, 20, './img/imagenes_producto_remeras/5.jpg', 'Remeras');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Remera Emily 06', 2500, 20, './img/imagenes_producto_remeras/6.jpg', 'Remeras');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Sweater Emily 01', 3800, 15, './img/imagenes_producto_sweaters/1.jpg', 'Sweaters');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Sweater Emily 02', 3800, 15, './img/imagenes_producto_sweaters/2.jpg', 'Sweaters');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Sweater Emily 03', 3800, 15, './img/imagenes_producto_sweaters/3.jpg', 'Sweaters');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Vestidos Emily 01', 3800, 15, './img/imagenes_producto_vestidosyfaldas/1.jpg', 'Vestidos y Faldas');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Vestidos Emily 02', 3800, 15, './img/imagenes_producto_vestidosyfaldas/2.jpg', 'Vestidos y Faldas');
INSERT INTO producto (nombre, precio, stock, imagen, categoria) VALUES ('Vestidos Emily 03', 3800, 15, './img/imagenes_producto_vestidosyfaldas/3.jpg', 'Vestidos y Faldas');
